# Generated by Django 5.0.3 on 2024-04-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_rename_tickets_events_ticket_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='events',
            name='ticket_type',
            field=models.ManyToManyField(related_name='events', to='events_app.tickets'),
        ),
    ]
