# Generated by Django 5.0.3 on 2024-04-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_remove_events_ticket_type_events_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_of_seats',
            field=models.IntegerField(null=True),
        ),
    ]
